# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Project docs to GitHub Pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci

      - name: Set up Git
        uses: actions/setup-git@v2.4.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          email: felipeflohrlol@gmail.com
          name: Felipe Matheus Flohr

      - name: Install Dependencies
        run: npm install

      - name: Add node_modules/.bin to PATH
        run: export PATH="./node_modules/.bin:$PATH"

      - name: Generate docs
        run: npm run doc:generate

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: docs

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
